### ISSUE TITLE
Error in checkForRemoteErrors(val) :  3 nodes produced errors

### ISSUE THREAD

**Issue by gpasi** [thierrygosselin/assigner#15]
**Describe the bug**
When I tried to work through the first example on http://thierrygosselin.github.io/assigner/articles/get_started.html (Data 1: high structure), I always got the following error messages (see below).

**To Reproduce**
Include the steps to reproduce the behavior:
- the exact command (function, arguments, values) used:
test1 <- assigner::assignment_ngs(
  data = data,
  assignment.analysis = "gsi_sim",
  markers.sampling = "ranked", 
  thl = 0.2,
  iteration.method = 5
)

* the complete error message you're getting
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: 'assignment_data_iteration_1_markers_497.output.txt' does not exist in current working directory ('C:/Users/gp/Documents/assignment_analysis_method_ranked_20190808@1453/assignment_1').
In addition: There were 18 warnings (use warnings() to see them)

Computation time, overall: 577 sec
########################## assignment_ngs completed ############################
> warnings()
Warnmeldungen:
1: In serialize(data, node$con) :
  'package:stats' may not be available when loading
2: In serialize(data, node$con) :
  'package:stats' may not be available when loading
3: In serialize(data, node$con) :
  'package:stats' may not be available when loading
4: In serialize(data, node$con) :
  'package:stats' may not be available when loading
5: In serialize(data, node$con) :
  'package:stats' may not be available when loading
6: In serialize(data, node$con) :
  'package:stats' may not be available when loading
7: In serialize(data, node$con) :
  'package:stats' may not be available when loading
8: In serialize(data, node$con) :
  'package:stats' may not be available when loading
9: In serialize(data, node$con) :
  'package:stats' may not be available when loading
10: In serialize(data, node$con) :
  'package:stats' may not be available when loading
11: In serialize(data, node$con) :
  'package:stats' may not be available when loading
12: In serialize(data, node$con) :
  'package:stats' may not be available when loading
13: In serialize(data, node$con) :
  'package:stats' may not be available when loading
14: In serialize(data, node$con) :
  'package:stats' may not be available when loading
15: In serialize(data, node$con) :
  'package:stats' may not be available when loading
16: In serialize(data, node$con) :
  'package:stats' may not be available when loading
17: In serialize(data, node$con) :
  'package:stats' may not be available when loading
18: In serialize(data, node$con) :
  'package:stats' may not be available when loading
(truncated here)

* the output of `devtools::session_info()`
> devtools::session_info()
- Session info --------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  German_Switzerland.1252     
 ctype    German_Switzerland.1252     
 tz       Europe/Berlin               
 date     2019-08-08                  

- Packages ------------------------------------------------------------------------------------------------------------------------------------
 package     * version  date       lib source                                   
 ade4          1.7-13   2018-08-31 [1] CRAN (R 3.6.1)                           
 adegenet      2.1.1    2018-02-02 [1] CRAN (R 3.6.1)                           
 ape           5.3      2019-03-17 [1] CRAN (R 3.6.1)                           
 assertthat    0.2.1    2019-03-21 [1] CRAN (R 3.6.1)                           
 assigner    * 0.5.6    2019-08-08 [1] Github (thierrygosselin/assigner@b941111)
 backports     1.1.4    2019-04-10 [1] CRAN (R 3.6.0)                           
 boot          1.3-22   2019-04-02 [2] CRAN (R 3.6.1)                           
 callr         3.3.1    2019-07-18 [1] CRAN (R 3.6.1)                           
 class         7.3-15   2019-01-01 [2] CRAN (R 3.6.1)                           
 classInt      0.3-3    2019-04-26 [1] CRAN (R 3.6.1)                           
 cli           1.1.0    2019-03-19 [1] CRAN (R 3.6.1)                           
 cluster       2.1.0    2019-06-19 [2] CRAN (R 3.6.1)                           
 coda          0.19-3   2019-07-05 [1] CRAN (R 3.6.1)                           
 colorspace    1.4-1    2019-03-18 [1] CRAN (R 3.6.1)                           
 crayon        1.3.4    2017-09-16 [1] CRAN (R 3.6.1)                           
 curl          4.0      2019-07-22 [1] CRAN (R 3.6.1)                           
 DBI           1.0.0    2018-05-02 [1] CRAN (R 3.6.1)                           
 deldir        0.1-23   2019-07-31 [1] CRAN (R 3.6.1)                           
 desc          1.2.0    2018-05-01 [1] CRAN (R 3.6.1)                           
 devtools    * 2.1.0    2019-07-06 [1] CRAN (R 3.6.1)                           
 digest        0.6.20   2019-07-04 [1] CRAN (R 3.6.1)                           
 dplyr         0.8.3    2019-07-04 [1] CRAN (R 3.6.1)                           
 e1071         1.7-2    2019-06-05 [1] CRAN (R 3.6.1)                           
 expm          0.999-4  2019-03-21 [1] CRAN (R 3.6.1)                           
 fs            1.3.1    2019-05-06 [1] CRAN (R 3.6.1)                           
 gdata         2.18.0   2017-06-06 [1] CRAN (R 3.6.0)                           
 ggplot2       3.2.0    2019-06-16 [1] CRAN (R 3.6.0)                           
 glue          1.3.1    2019-03-12 [1] CRAN (R 3.6.1)                           
 gmodels       2.18.1   2018-06-25 [1] CRAN (R 3.6.1)                           
 gtable        0.3.0    2019-03-25 [1] CRAN (R 3.6.1)                           
 gtools        3.8.1    2018-06-26 [1] CRAN (R 3.6.0)                           
 hms           0.5.0    2019-07-09 [1] CRAN (R 3.6.1)                           
 htmltools     0.3.6    2017-04-28 [1] CRAN (R 3.6.1)                           
 httpuv        1.5.1    2019-04-05 [1] CRAN (R 3.6.1)                           
 igraph        1.2.4.1  2019-04-22 [1] CRAN (R 3.6.1)                           
 KernSmooth    2.23-15  2015-06-29 [2] CRAN (R 3.6.1)                           
 later         0.8.0    2019-02-11 [1] CRAN (R 3.6.1)                           
 lattice       0.20-38  2018-11-04 [2] CRAN (R 3.6.1)                           
 lazyeval      0.2.2    2019-03-15 [1] CRAN (R 3.6.1)                           
 LearnBayes    2.15.1   2018-03-18 [1] CRAN (R 3.6.0)                           
 magrittr      1.5      2014-11-22 [1] CRAN (R 3.6.1)                           
 MASS          7.3-51.4 2019-03-31 [2] CRAN (R 3.6.1)                           
 Matrix        1.2-17   2019-03-22 [2] CRAN (R 3.6.1)                           
 memoise       1.1.0    2017-04-21 [1] CRAN (R 3.6.1)                           
 mgcv          1.8-28   2019-03-21 [2] CRAN (R 3.6.1)                           
 mime          0.7      2019-06-11 [1] CRAN (R 3.6.0)                           
 munsell       0.5.0    2018-06-12 [1] CRAN (R 3.6.1)                           
 nlme          3.1-140  2019-05-12 [2] CRAN (R 3.6.1)                           
 pbmcapply     1.5.0    2019-07-10 [1] CRAN (R 3.6.1)                           
 permute       0.9-5    2019-03-12 [1] CRAN (R 3.6.1)                           
 pillar        1.4.2    2019-06-29 [1] CRAN (R 3.6.1)                           
 pkgbuild      1.0.4    2019-08-05 [1] CRAN (R 3.6.1)                           
 pkgconfig     2.0.2    2018-08-16 [1] CRAN (R 3.6.1)                           
 pkgload       1.0.2    2018-10-29 [1] CRAN (R 3.6.1)                           
 plyr          1.8.4    2016-06-08 [1] CRAN (R 3.6.1)                           
 prettyunits   1.0.2    2015-07-13 [1] CRAN (R 3.6.1)                           
 processx      3.4.1    2019-07-18 [1] CRAN (R 3.6.1)                           
 promises      1.0.1    2018-04-13 [1] CRAN (R 3.6.1)                           
 ps            1.3.0    2018-12-21 [1] CRAN (R 3.6.1)                           
 purrr         0.3.2    2019-03-15 [1] CRAN (R 3.6.1)                           
 R6            2.4.0    2019-02-14 [1] CRAN (R 3.6.1)                           
 radiator      1.1.1    2019-08-08 [1] Github (thierrygosselin/radiator@d79b062)
 Rcpp          1.0.2    2019-07-25 [1] CRAN (R 3.6.1)                           
 readr         1.3.1    2018-12-21 [1] CRAN (R 3.6.1)                           
 remotes       2.1.0    2019-06-24 [1] CRAN (R 3.6.1)                           
 reshape2      1.4.3    2017-12-11 [1] CRAN (R 3.6.1)                           
 rlang         0.4.0    2019-06-25 [1] CRAN (R 3.6.1)                           
 rprojroot     1.3-2    2018-01-03 [1] CRAN (R 3.6.1)                           
 rstudioapi    0.10     2019-03-19 [1] CRAN (R 3.6.1)                           
 scales        1.0.0    2018-08-09 [1] CRAN (R 3.6.1)                           
 seqinr        3.4-5    2017-08-01 [1] CRAN (R 3.6.1)                           
 sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 3.6.1)                           
 sf            0.7-7    2019-07-24 [1] CRAN (R 3.6.1)                           
 shiny         1.3.2    2019-04-22 [1] CRAN (R 3.6.1)                           
 sp            1.3-1    2018-06-05 [1] CRAN (R 3.6.1)                           
 spData        0.3.0    2019-01-07 [1] CRAN (R 3.6.1)                           
 spdep         1.1-2    2019-04-05 [1] CRAN (R 3.6.1)                           
 stringi       1.4.3    2019-03-12 [1] CRAN (R 3.6.0)                           
 stringr       1.4.0    2019-02-10 [1] CRAN (R 3.6.1)                           
 testthat      2.2.1    2019-07-25 [1] CRAN (R 3.6.1)                           
 tibble        2.1.3    2019-06-06 [1] CRAN (R 3.6.1)                           
 tidyselect    0.2.5    2018-10-11 [1] CRAN (R 3.6.1)                           
 units         0.6-3    2019-05-03 [1] CRAN (R 3.6.1)                           
 usethis     * 1.5.1    2019-07-04 [1] CRAN (R 3.6.1)                           
 vctrs         0.2.0    2019-07-05 [1] CRAN (R 3.6.1)                           
 vegan         2.5-5    2019-05-12 [1] CRAN (R 3.6.1)                           
 withr         2.1.2    2018-03-15 [1] CRAN (R 3.6.1)                           
 xtable        1.8-4    2019-04-21 [1] CRAN (R 3.6.1)                           
 zeallot       0.1.0    2018-01-28 [1] CRAN (R 3.6.1)                           

[1] C:/Users/gp/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.1/library

* complete data required to reproduce the problem, a subset of it. The data remains confidential.
data set from the example, obtained via the command
data <- data_assigner_sim_01

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53909648/62715409-bfac0980-ba00-11e9-94a8-8357fdfb091e.png)

**Comment by thierrygosselin** [comment]
I'm not able to reproduce the error on my Mac. It's definitely related to your PC and the parallelization process. What do you get when this is entered:

```
parallel::detectCores()
```

**Comment by thierrygosselin** [comment]
Also, try this to confirm my hypothesis above:

```
test1 <- assigner::assignment_ngs(
  data = data,
  assignment.analysis = "gsi_sim",
  markers.sampling = "ranked", 
  thl = 0.2,
  iteration.method = 5,
  parallel.core = 1
)
```

**Comment by gpasi** [comment]
Thanks for the quick reply.

Here is the output:
> parallel::detectCores()
[1] 4

Shall I still run the other code you sent?

Von: Thierry Gosselin [mailto:notifications@github.com]
Gesendet: Donnerstag, 8. August 2019 17:43
An: thierrygosselin/assigner
Cc: Pasinelli Gilberto; Author
Betreff: Re: [thierrygosselin/assigner] Error in checkForRemoteErrors(val) : 3 nodes produced errors (#15)


I'm not able to reproduce the error on my Mac. It's definitely related to your PC and the parallelization process. What do you get when this is entered:

parallel::detectCores()

**Comment by thierrygosselin** [comment]
yes, do try this:

```
test1 <- assigner::assignment_ngs(
  data = data,
  assignment.analysis = "gsi_sim",
  markers.sampling = "ranked", 
  thl = 0.2,
  iteration.method = 5,
  parallel.core = 1
)
```

**Comment by gpasi** [comment]
I’ll try on Monday. Need to catch a train and are off tomorrow…

Thanks for your help so far!
Gilberto

Von: Thierry Gosselin [mailto:notifications@github.com]
Gesendet: Donnerstag, 8. August 2019 17:49
An: thierrygosselin/assigner
Cc: Pasinelli Gilberto; Author
Betreff: Re: [thierrygosselin/assigner] Error in checkForRemoteErrors(val) : 3 nodes produced errors (#15)


yes, do try this:

test1 <- assigner::assignment_ngs(

  data = data,

  assignment.analysis = "gsi_sim",

  markers.sampling = "ranked",

  thl = 0.2,

  iteration.method = 5,

  parallel.core = 1

)

**Comment by thierrygosselin** [comment]
Ok my guess is that you have a problem with your core + R.

open the issue if still an error

**Comment by gpasi** [comment]
Hi again

The problem does not seem to be resolved yet:

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> rm(list = ls())

> library(assigner)
Registered S3 method overwritten by 'spdep':
  method   from
  plot.mst ape

> data <- data_assigner_sim_01

> test1 <- assigner::assignment_ngs(
+   data = data,
+   assignment.analysis = "gsi_sim",
+   markers.sampling = "ranked",
+   thl = 0.2,
+   iteration.method = 5,
+   parallel.core = 1
+ )
################################################################################
########################## assigner::assignment_ngs ############################
################################################################################
Execution date/time: 20190812@1304
Assignment analysis with gsi_sim
Folder created: assignment_analysis_method_ranked_20190812@1304
Calibrating REF/ALT alleles...
Subsampling: not selected
Conducting Assignment analysis using Training, Holdout, Leave-one-out
Using training samples to rank markers based on Fst
Holdout samples saved in your folder
Starting parallel computations, for progress monitor activity in folder...
Error in checkForRemoteErrors(val) :
  one node produced an error: 'assignment_data_iteration_1_markers_497.output.txt' does not exist in current working directory ('C:/Users/gp/Documents/assignment_analysis_method_ranked_20190812@1304/assignment_1').
In addition: There were 18 warnings (use warnings() to see them)

Computation time, overall: 110 sec
########################## assignment_ngs completed ############################
> names(test1)
Error: object 'test1' not found


Von: Thierry Gosselin [mailto:notifications@github.com]
Gesendet: Donnerstag, 8. August 2019 18:13
An: thierrygosselin/assigner
Cc: Pasinelli Gilberto; Author
Betreff: Re: [thierrygosselin/assigner] Error in checkForRemoteErrors(val) : 3 nodes produced errors (#15)


Ok my guess is that you have a problem with your core + R.

open the issue if still an error
