### ISSUE TITLE
Error: Argument 1 must have names

### ISSUE THREAD

**Issue by NadyaMamoozadeh** [thierrygosselin/assigner#16]
Hello! I am running the following code in R v3.5.1 using new installs of the radiator and assigner R packages (installed via devtools Sep 14, 2019) on my Mac:

test.tidy = radiator::tidy_genomic_data(data="test.gen", strata="subset_strata.txt")

assign1 <- assigner::assignment_ngs(
  data = test.tidy,
  assignment.analysis = "gsi_sim",
  markers.sampling = "ranked", 
  thl = 0.2,
  iteration.method = 5
)

I get the following error:

##################### assigner::assignment_ngs ################
Execution date/time: 20190914@1348
Assignment analysis with gsi_sim
Folder created: assignment_analysis_method_ranked_20190914@1348
Subsampling: not selected
Conducting Assignment analysis using Training, Holdout, Leave-one-out
Using training samples to rank markers based on Fst
Holdout samples saved in your folder
Starting parallel computations, for progress monitor activity in folder...
Error: Argument 1 must have names

Computation time, overall: 1 sec
###############assignment_ngs completed ############

I've attached my input files (subsets of my full dataset) so that you can recreate the issue. I am using 'test.gen' as input with the attached file, not 'test.txt' (will not let me upload with *.gen file extension). I see an [earlier bug report](https://github.com/thierrygosselin/assigner/issues/12) from a user that was getting the same error but changing the file extension did not fix the problem. I've also attached the output from devtools::session_info(). I should also note that I get the same error when attempting to run the same code but using the test datasets provided in the assigner vignettes (data_assigner_sim_01, data_assigner_sim_02). Please let me know if any other information would be helpful! Thanks!

[devtools_session_info.txt](https://github.com/thierrygosselin/assigner/files/3613002/devtools_session_info.txt)

[subset_strata.txt](https://github.com/thierrygosselin/assigner/files/3612998/subset_strata.txt)

[test.txt](https://github.com/thierrygosselin/assigner/files/3612999/test.txt)

**Comment by thierrygosselin** [comment]
Hi nrcombs,
I’ll have a look today at the 
Thanks for reporting 
Cheers
Thierry

**Comment by NadyaMamoozadeh** [comment]
Thanks Thierry for your response! After posting I realized that the issue must be with gsi_sim (perhaps either broken code within the gsi_sim algorithm itself, or its implementation of assigner). The dapc module works great. Will look forward to using the gsi_sim capabilities when available, thanks for this user-friendly program!

**Comment by PeiwenLi** [comment]
Hi nrcombs and Thierry,
I ran into the same error following the script in https://thierrygosselin.github.io/assigner/articles/get_started.html under R v3.5.3 with radiator v1.0.0 and assinger v0.5.6. 
Would changing back to older version R be helpful? 
Thanks,
Peiwen

**Comment by PeiwenLi** [comment]
Problem was automatically solved after updating to R v3.6.2.
Peiwen

**Comment by thierrygosselin** [comment]
This problem originate from another package it should now be fix.
