### ISSUE TITLE
Function assignment_mixture no longer available in v0.5.7?

### ISSUE THREAD

**Issue by PeiwenLi** [thierrygosselin/assigner#19]
Hi!
I used _assigner_ to to perform assignments on a group of baseline samples a month ago. Now I get a new set of samples of unknown origins, and I would like to assign this batch to the baseline samples. Previously we have the function _assignment_mixture_ to perform such kind of tasks, but it seems this function was disabled in the latest _assigner_ v0.5.7?
Thanks a lot,
Peiwen

**Comment by thierrygosselin** [comment]
Dear Peiwen, I havent had time to make the function work with newer version, and/or compare it with package [rubias](https://github.com/eriqande/rubias). 

I suggest you use rubias if it's to re-assign unknowns ...
Thierry
