### ISSUE TITLE
Error while using the subsampling option in Fst_WC84()

### ISSUE THREAD

**Issue by usmart31** [thierrygosselin/assigner#21]
Hi, I am interested in using the Fst_WC84() with subsampling. However, while getting familiar with your function by using datasets provided by you, I am running into the following error : 

**library(assigner)
data <- data_assigner_sim_01
assigner::fst_WC84(data, filename = "Test", subsample = 36, iteration.subsample = 20)

 Error: Argument 1 must have names 

7. stop(structure(list(message = "Argument 1 must have names", call = NULL, 
    cppstack = NULL), class = c("Rcpp::exception", "C++Error", 
"error", "condition"))) 
6. bind_rows_(x, .id) 
5. dplyr::bind_rows(res$pairwise.fst.subsample) 
4. eval(lhs, parent, parent) 
3. eval(lhs, parent, parent) 
2. dplyr::bind_rows(res$pairwise.fst.subsample) %>% dplyr::group_by(POP1, 
    POP2) %>% dplyr::summarise_all(.tbl = ., .funs = mean, na.rm = TRUE) %>% 
    dplyr::mutate(ITERATIONS = rep(iteration.subsample, n())) at fst_WC84.R#649
1. assigner::fst_WC84(data, filename = "Test", subsample = 36, iteration.subsample = 20 )_** 

I have read other reports about a similar issue, but that is all in the context of assignment analysis and not Fst calculations. Is this a bug or am I missing something here?

Thank you,

P.S. The function runs just fine without the subsampling argument.

**Comment by thierrygosselin** [comment]
Should work now, make sure you have dplyr v. 1.0.0 installed 
Re-open the issue if you're still having problems
