### ISSUE TITLE
Reading VCF... Error in SeqArray::seqOpen(gds.fn = data.safe$result, readonly = FALSE) :   is.character(gds.fn) is not TRUE

### ISSUE THREAD

**Issue by saat-mics** [thierrygosselin/assigner#26]
Hi,
when using assigner
mf<-radiator::genomic_converter(data="/gpfs/gpfs0/genomdata/Ecogenome/periwinkle/stacks/populations/s1_50%_50%_217ind_fullfiltered.recode.vcf", strata="/gpfs/gpfs0/genomdata/Ecogenome/periwinkle/stacks/populations/s1_pop") %>%dplyr::glimpse()

I get the following error:

################################################################################
################################################################################
Execution date@time: 20230223@1627
Folder created: -277260_radiator_genomic_converter_20230223@1627
Function call and arguments stored in: [radiator_genomic_converter_args_20230223@1627.tsv](mailto:radiator_genomic_converter_args_20230223@1627.tsv)
Filters parameters file generated: [filters_parameters_20230223@1627.tsv](mailto:filters_parameters_20230223@1627.tsv)

Reading VCF...
Error in SeqArray::seqOpen(gds.fn = data.safe$result, readonly = FALSE) :
is.character(gds.fn) is not TRUE

Computation time, overall: 6 sec

Computation time, overall: 14 sec
######################### completed genomic_converter ##########################
✖ Importing data: vcf.file [6.7s]

could you please help me with this?

**Comment by thierrygosselin** [comment]
unable to reproduce. 
Follow guidelines for issues/bugs please
