### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by ddrinan** [thierrygosselin/assigner#7]
Hi, I'm trying to install assigner on a machine running Windows 10 and R 3.3.0. I get an error that I need to update package 'pmbcapply' to version >= 1.3. My understanding is that this package only goes up to 1.0 for Windows. Do you have a work around for this (or am I wrong)? Thanks for any help you can provide.

**Comment by thierrygosselin** [comment]
Try this
devtools::install_github("kvnkuang/pbmcapply")

Next issue will have a fix for this

**Comment by ddrinan** [comment]
Thanks for your response. I tried the following.

> library(devtools)
Warning message:
package ‘devtools’ was built under R version 3.3.1 
> devtools::install_github("kvnkuang/pbmcapply")
Downloading GitHub repo kvnkuang/pbmcapply@master
from URL https://api.github.com/repos/kvnkuang/pbmcapply/zipball/master
Installing pbmcapply
"C:/PROGRA~1/R/R-33~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/dan/AppData/Local/Temp/RtmpAh12MD/devtoolsc707e6b6176/kvnkuang-pbmcapply-f13d0e5"  \
  --library="C:/Users/dan/Documents/R/win-library/3.3" --install-tests 

ERROR:  Unix-only package
* removing 'C:/Users/dan/Documents/R/win-library/3.3/pbmcapply'
Error: Command failed (1)

Perhaps it is only for *nix?

**Comment by thierrygosselin** [comment]
see the [update](https://github.com/thierrygosselin/assigner#new-features)
